#!/usr/bin/env ruby
#require File.dirname(__FILE__) + '/../config/boot'
require File.dirname(__FILE__) + '/../config/environment'

require 'fastercsv'

FasterCSV.foreach('entries.csv', :headers => :first_row) do |row|
  e = Organization.new
  row.each do |k,v|
    if e.respond_to? k
      e[k] = v
    end
  end
  e.save or warn "failure"
end
