class AccessRule < ActiveRecord::Base
  AccessRule::ACCESS_TYPE_PUBLIC = 'PUBLIC'
  AccessRule::ACCESS_TYPE_LOGGEDIN = 'LOGGEDIN'
  AccessRule::ACCESS_TYPE_PRIVATE = 'PRIVATE'
  AccessRule::ACCESS_TYPES = [ACCESS_TYPE_PUBLIC, ACCESS_TYPE_LOGGEDIN, ACCESS_TYPE_PRIVATE]
end
